version: '3.7'
services:
  postgresdb:
    container_name: history-generator
    image: postgres
    restart: unless-stopped
    command: postgres -c 'max_connections=200'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
